version: 2.1

jobs:
    install:
        docker:
            - image: svalinn/pymoab-visit-py2-18.04
              auth:
                username: $DOCKERHUB_USER
                password: $DOCKERHUB_PASS
        steps:
            - checkout
            - run:  pip install . --user

    test:
        docker:
            - image: svalinn/pymoab-visit-py2-18.04
              auth:
                username: $DOCKERHUB_USER
                password: $DOCKERHUB_PASS
        steps:
            - checkout
            - run:
                command: |
                    apt install -y hdf5-tools
                    pip install coverage meshio
                    coverage run --source=./IsogeomGenerator/ --omit=./IsogeomGenerator/__init__.py -m pytest
                    coverage report
                    coverage html
            - store_artifacts:
                path: htmlcov

workflows:
    build:
        jobs:
            - install:
                context: dockerhub
            - test:
                context: dockerhub
