version: 2.1

jobs:
    install_test:
        docker:
            - image: kkiesling/pymoab-visit-py2-18.04
        steps:
            - checkout
            - run:  pip install -e . --user
            - run:
                working_directory: tests/
                command: pytest

workflows:
    build:
        jobs:
            - install_test
